### ISSUE TITLE
Update `testthat` infrastructure?

### ISSUE THREAD

**Issue by jrdnbradford** [ropensci/gitignore#24]
It looks like this project is using the 2nd edition of `testthat`. Any interest in bumping the version to 3? If so, I wouldn't mind doing the work, and adding some tests for `gi_available_templates()`. From the looks of it, doesn't seem like any tests need to be rewritten to be 3e compatible.

**Comment by PMassicotte** [comment]
Hi and thank you for reaching out.

I have not looked at the new features proposed in the version 3. Do you see any benefits of switching?

**Comment by jrdnbradford** [comment]
I do. See https://testthat.r-lib.org/articles/third-edition.html and https://www.tidyverse.org/blog/2022/02/upkeep-testthat-3/ for the full story, but in short:

- better comparability between objects
- better reproducible output
- better integration with `devtools` and `usethis`
- easier testing

In my own fork I was able to update to 3e with no issues. It's not a particularly big change since this repo doesn't use any of the deprecated functions, but doing this will keep things up to date and improve the current testing.

**Comment by PMassicotte** [comment]
Sounds good, PR welcome.
